### Crear

POST http://localhost:8800/login HTTP/1.1
content-type: application/json

{
            "user": "euge",
            "email": "eugenionoche2@gmail.com"
}

### GET

GET http://localhost:8000/api/v1/stock/articulos HTTP/1.1
content-type: application/json
